// 'use server'

export * from './subject'
export * from './class'
export * from './announcement'
export * from './assignment'
export * from './exam'
export * from './lesson'
export * from './parent'
export * from './result'
export * from './student'
export * from './teacher'
export * from './event'
